// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJiwS8gua8HDaPtdQZ8AyETyMrSWuBJS0',
    appId: '1:336565084591:web:038bd369780ad5e03e8f5a',
    messagingSenderId: '336565084591',
    projectId: 'chattest-edcd4',
    authDomain: 'chattest-edcd4.firebaseapp.com',
    storageBucket: 'chattest-edcd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDldbrMR6CvIJ0_FmVz51VoAyGLpX8zOm0',
    appId: '1:336565084591:android:1db9e4188a7d71863e8f5a',
    messagingSenderId: '336565084591',
    projectId: 'chattest-edcd4',
    storageBucket: 'chattest-edcd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvtObJrUf3DZdORWDJLmfThLz1UiQQUhs',
    appId: '1:336565084591:ios:cfd385d5b1f49d633e8f5a',
    messagingSenderId: '336565084591',
    projectId: 'chattest-edcd4',
    storageBucket: 'chattest-edcd4.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );
}
